version: 0.0
os: linux
files:
  - source: web.py
    destination: /home/ubuntu/py-features-api/
  - source: api.py
    destination: /home/ubuntu/py-features-api/
hooks:
   AfterInstall:
     - location: scripts/restart_supervisor.sh
       timeout: 180
